### ISSUE TITLE
Download links missing for 2019.08.2 and 2019.08.3

### ISSUE THREAD

**Issue by Matze0811** [tine20/tine20#7122]
Hi Folks, Im missing the downloads named above. I just want to update my installation from 2019.08.2 to the actual (2019.12.3) but i've got issues to upgrade to 2019.08.4. so i decided to do the long way, update after update but i can't download 2019.08.3, the link is broken.

Maybe you can do something to?

**Comment by lab-at-nohl** [comment]
I have no idea why these all-in-one packages are gone. But if you really need to update including all minors (2019.08.1 and 2019.08.4 are available!), you could go with the source.zip. Those are available and - as long as you update by cli - are sufficient. 

In the meantime it would be best to figure out what breaks your update chain. A log file, level DEBUG would be nice (from 2019.08.1 to 2019.08.4). 

The official way is btw
1. always go to the last minor of a major version
2. update to the new major

Johannes

**Comment by Matze0811** [comment]
Thanks Lab-at-nohl for advise.
When i try to update, there are some deprecated function errors (Im using php7.2 on a debian machine)

and a record not found in model_role.

`Tinebase_Core::errorHandler::712 array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /var/www/elektrohd/tine20-current/vendor/zendframework/zendframework1/library/Zend/Registry.php::206 (8192)
Tinebase_Core::errorHandler::713 #0 /var/www/elektrohd/tine20-current/vendor/zendframework/zendframework1/library/Zend/Registry.php(206): Tinebase_Core::errorHandler()
#1 /var/www/elektrohd/tine20-current/vendor/zendframework/zendframework1/library/Zend/Registry.php(145): Zend_Registry->offsetExists()
#2 /var/www/elektrohd/tine20-current/Tinebase/Core.php(1444): Zend_Registry::get()
#3 /var/www/elektrohd/tine20-current/Tinebase/Core.php(1517): Tinebase_Core::get()
#4 /var/www/elektrohd/tine20-current/Tinebase/Log/Formatter.php(121): Tinebase_Core::getConfig()
#5 /var/www/elektrohd/tine20-current/Tinebase/Log.php(117): Tinebase_Log_Formatter->__construct()
#6 /var/www/elektrohd/tine20-current/Tinebase/Log.php(148): Tinebase_Log->getFormatter()
#7 /var/www/elektrohd/tine20-current/Tinebase/Core.php(799): Tinebase_Log->addWriterByConfig()
#8 /var/www/elektrohd/tine20-current/Tinebase/Core.php(1559): Tinebase_Core::setupLogger()
#9 /var/www/elektrohd/tine20-current/Tinebase/Core.php(1035): Tinebase_Core::getLogger()
#10 /var/www/elektrohd/tine20-current/Setup/Core.php(211): Tinebase_Core::setupDatabaseConnection()
#11 /var/www/elektrohd/tine20-current/Setup/Core.php(39): Setup_Core::setupDatabaseConnection()
#12 /var/www/elektrohd/tine20-current/Setup/Server/Cli.php(134): Setup_Core::initFramework()
#13 /var/www/elektrohd/tine20-current/Setup/Core.php(117): Setup_Server_Cli->handle()
#14 /var/www/elektrohd/tine20-current/setup.php(14): Setup_Core::dispatchRequest()
#15 {main}
Tinebase_Exception_NotFound: Tinebase_Model_Role record with id = 564cec9738f78346c55b871961f8224cbe110002 not found! in /var/www/elektrohd/tine20-current/Tinebase/Backend/Sql/Abstract.php:314
Stack trace:`

[tine20.log](https://github.com/tine20/tine20/files/3992354/tine20.log)

**Comment by pschuele** [comment]
hi,
we removed those old packages because you do not need them for the update. just use the latest version package for each major release.

> Tinebase_Core::errorHandler::712 array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead

this looks like you are already using php 7.4! see #7125 
we don't support this atm, but support will come with the next release. we already fixed the Zend_Registry problem here (for local patching) -> https://github.com/tine20/zendframework1/commit/44d5fe350256b5a4316ca9e11ad0012694272f64

**Comment by Matze0811** [comment]
thanks pschuele.
don't know why my cli was linked to 7.4 and apache still uses 7.2, i've corrected this, both now on 7.2 as recommended.
But i still get:
`Tinebase_Exception_NotFound: Tinebase_Model_Role record with id = 52a96d635008717b932caaacf2ef01e28d31708a not found! in /var/www/elektrohd/tine20-current/Tinebase/Backend/Sql/Abstract.php:314
Stack trace:
#0 /var/www/elektrohd/tine20-current/Tinebase/Backend/Sql/Abstract.php(282): Tinebase_Backend_Sql_Abstract->getRawDataByProperty('52a96d635008717...', 'id', false)
#1 /var/www/elektrohd/tine20-current/Tinebase/Backend/Sql/Abstract.php(251): Tinebase_Backend_Sql_Abstract->getByProperty('52a96d635008717...', 'id', false)
#2 /var/www/elektrohd/tine20-current/Tinebase/Controller/Record/Abstract.php(522): Tinebase_Backend_Sql_Abstract->get('52a96d635008717...', false)
#3 /var/www/elektrohd/tine20-current/Tinebase/Acl/Roles.php(975): Tinebase_Controller_Record_Abstract->get('52a96d635008717...', NULL, true, false)
#4 /var/www/elektrohd/tine20-current/Tinebase/Acl/Roles.php(654): Tinebase_Acl_Roles->get('52a96d635008717...')
#5 /var/www/elektrohd/tine20-current/Tinebase/Acl/Roles.php(589): Tinebase_Acl_Roles->removeRoleMember('52a96d635008717...', Array)
#6 /var/www/elektrohd/tine20-current/Setup/Controller.php(938): Tinebase_Acl_Roles->setRoleMemberships(Array, Array)
#7 /var/www/elektrohd/tine20-current/Setup/Controller.php(759): Setup_Controller->_prepareUpdate(Object(Tinebase_Model_FullUser))
#8 /var/www/elektrohd/tine20-current/Setup/Controller.php(643): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '12')
#9 /var/www/elektrohd/tine20-current/Setup/Controller.php(522): Setup_Controller->_legacyUpdateApplications(Object(Tinebase_Record_RecordSetFast))
#10 /var/www/elektrohd/tine20-current/Setup/Frontend/Cli.php(467): Setup_Controller->updateApplications()
#11 /var/www/elektrohd/tine20-current/Setup/Frontend/Cli.php(451): Setup_Frontend_Cli->_updateApplications()
#12 /var/www/elektrohd/tine20-current/Setup/Frontend/Cli.php(81): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#13 /var/www/elektrohd/tine20-current/Setup/Server/Cli.php(141): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#14 /var/www/elektrohd/tine20-current/Setup/Core.php(117): Setup_Server_Cli->handle()
#15 /var/www/elektrohd/tine20-current/setup.php(14): Setup_Core::dispatchRequest()
#16 {main}`

is it possible to produce a dummy-record or something?

**Comment by Matze0811** [comment]
cause ist answered where the download-links are, ill close here and open another issue for my persistend problem.
