### ISSUE TITLE
update fails from 2020.08.7 to 2021.02.4 (also from 2021.02.2)

### ISSUE THREAD

**Issue by My1** [tine20/tine20#7333]
This is a log data piece from 2020.08.7 (and as far as I remember the updater should be able to run from the latest minor of the last major to the current version, not sure if you can skip minors when updating, like from a .2 to a .4)

```
fcac57 - setupuser - 2021-10-01T11:12:52+00:00 WARN (4): Setup_Update_Abstract::addApplicationUpdate::138Cannot update to equal version: 14.11 Version update missing in update script?
fcac57 - setupuser - 2021-10-01T11:12:52+00:00 ERR (3): Setup_Controller::updateApplications::562 no such field (container_id) in this filter model
fcac57 - setupuser - 2021-10-01T11:12:52+00:00 ERR (3): Setup_Controller::updateApplications::563 #0 /var/www/html/Tinebase/Controller/Record/Abstract.php(2416): Tinebase_Model_Filter_FilterGroup->createFilter()
#1 /var/www/html/Tinebase/Controller/Record/Abstract.php(298): Tinebase_Controller_Record_Abstract->checkFilterACL()
#2 /var/www/html/Tinebase/ImportExportDefinition.php(92): Tinebase_Controller_Record_Abstract->search()
#3 /var/www/html/Addressbook/Setup/Update/13.php(137): Tinebase_ImportExportDefinition->getExportDefinitionsForApplication()
#4 /var/www/html/Setup/Controller.php(556): Addressbook_Setup_Update_13->update007()
#5 /var/www/html/Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
#6 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(231): Setup_Frontend_Json->updateApplications()
#7 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(603): Zend_Server_Abstract->_dispatch()
#8 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(206): Zend_Json_Server->_handle()
#9 /var/www/html/Setup/Server/Json.php(90): Zend_Json_Server->handle()
#10 /var/www/html/Setup/Core.php(117): Setup_Server_Json->handle()
#11 /var/www/html/setup.php(14): Setup_Core::dispatchRequest()
#12 {main
```

**Comment by csvarer** [comment]
I can confirm this behaviour as I have tried to update from 2021.02.3 to 2021.02.4 and the update works, you can login and use Tine20, but it still claims that Addressbook is version 14.1 where it should be 14.2 and it needs an update.

Thanks for supplying us with this great program
Claus

**Comment by lab-at-nohl** [comment]
> the updater should be able to run from the latest minor of the last major to the current version

That is correct and intended (imagine the update does not work with .1 but was fixed after that by .2). However, there might be situations where minor updates come with their own issues. Hence, when problems occur I usually try smaller steps (as you did by intermediate .2)

This could be the case here, too. Since the ERR is fired on the way in `Addressbook/Setup/Update/13.php(137): Tinebase_ImportExportDefinition->getExportDefinitionsForApplication()` I would recommend to install **2021.02.2 first**. The whole routine was introduced with 2021.02.3 and changed again in 2021.02.4. 

Actually, this is a duplicate to #7327. I am not sure how I can help you. I could see any unusual behaviour in the logs you provided there.

**Comment by My1** [comment]
> I would recommend to install 2021.02.2 first

the issue appears from 2021.02.2 as well as mentioned in title.

> Actually, this is a duplicate to #7327

okay interesting as here you get an actual error in the update itself rather than it updating fine and only spawning an error on the login afterward.

**Comment by lab-at-nohl** [comment]
To me both issues appear to be the same:

`no such field (container_id) in this filter model` in conjunction with Setup, 
`Tinebase_Exception_NotFound -> no such field (container_id) in this filter model` when running the app. 

Nevertheless, we need to acquire some more information. And as I said your log snippet must not taken from 2021.02.2 because the function wasn't there back then. That is why I would recommend to try an earlier version like 2021.02.2 or even better: fix the issue before update.

**Comment by My1** [comment]
it likely has the same cause, I wont deny that, just that it shows differently with .4

gonna do a rerun for logs with 2021.02.2

didnt do the logs for both when running the update from 02.2 as I wasnt sure whether or not skipping minors in the same (aka going from .2 to .4) is a supported upgrade path, while going from latest previous to any later is supposed to work as latest to latest has to work according to instructions.

**Comment by psieg** [comment]
Related but probably not the cause: I found it kept doing the last Tinebase update step (even if I used the GUI to update only Addressbook) because [this](https://github.com/tine20/tine20/blob/95258309d9d575bf26a87ac89d8640801cea171f/tine20/Tinebase/Setup/Update/14.php#L300) should be `RELEASE014_UPDATE011`. Changing that didn't fix the Addressbook update issue though.

**Comment by psieg** [comment]
But the cause for the Addressbook is similar: https://github.com/tine20/tine20/blob/95258309d9d575bf26a87ac89d8640801cea171f/tine20/Addressbook/Setup/Update/14.php#L24

**Comment by My1** [comment]
@lab-at-nohl okay finally had to time to try a clean install as described and apparently that works aside from the issue that addressbook reports the wrong version in setup. so TLDR wiki needs some fixing

**Comment by My1** [comment]
I closed the other but there's still the version issue on the addressbook which has its update problem, should that get a new issie

**Comment by ma-ef** [comment]
Issue still occurs for me as well. Tried to update 2021.02.1 to 2021.02.4 and the addressbook database version always stays 14.1 and cannot be updated to 14.2

**Comment by ma-ef** [comment]
Just udpated to 2021.12.1 successfully without any issue. Can be closed from my point of view. Thanks for the great work!

**Comment by pschuele** [comment]
thanks for the update :)
closing this ...
